version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'full'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'folder'
